---
title: "MATH 1051H-A: Lecture Links"
author: 'Dr. Wesley S. Burr'
date: 2020-12-03
output:
  xaringan::moon_reader:
    chakra: remark-latest.min.js
    lib_dir: libs
    nature:
      highlightStyle: tomorrow-night-bright
      highlightLines: true
      highlightLanguage: r
    includes:
      in_header: header.html
    countIncrementalSlides: false
    css: example.css
---

class: inverse

```{r include=FALSE}
library(ggplot2)
filter <- dplyr::filter
knitr::opts_chunk$set(warning=FALSE, message=FALSE, fig.width=10.5, fig.height=4, 
  comment=NA, rows.print=16)
theme_set(theme_gray(base_size = 24))
```

## Lecture Slide Links

The following slides have links to the lecture slides for **Section A** of MATH 1051H for
the 2019FA semester at Trent University. 

<br />

* the HTML slides are the canonical format
* the PDFs aren't bad
* the Powerpoints are kinda hideous, only use them if you really love Powerpoint
for some reason

---

class: inverse


## Week 01

**Lecture 01 - September 6**   

<a href="./Lecture01/Lecture01.html">HTML</a>; 
<a href="./Lecture01/Lecture01.pdf">PDF</a>;
<a href="./Lecture01/Lecture01.pptx">PPTX</a> (hideous)

<br />
**Lecture 02 - September 11**   

<a href="./Lecture02/Lecture02.html">HTML</a>; 
<a href="./Lecture02/Lecture02.pdf">PDF</a>;
<a href="./Lecture02/Lecture02.pptx">PPTX</a>


---

class: inverse

## Week 02

**Lecture 03 - September 13**

<a href="./Lecture03/Lecture03.html">HTML</a>; 
<a href="./Lecture03/Lecture03.pdf">PDF</a>;
<a href="./Lecture03/Lecture03.pptx">PPTX</a>

<br />
**Lecture 04 - September 18**

<a href="./Lecture04/Lecture04.html">HTML</a>; 
<a href="./Lecture04/Lecture04.pdf">PDF</a>;
<a href="./Lecture04/Lecture04.pptx">PPTX</a>; <br/>
<a href="https://rstudio.cloud/spaces/26689/project/532300">(RStudio Example)</a>

---

class: inverse

## Week 03

**Lecture 05 - September 20**

<a href="./Lecture05/Lecture05.html">HTML</a>; 
<a href="./Lecture05/Lecture05.pdf">PDF</a>;
<a href="./Lecture05/Lecture05.pptx">PPTX</a>

<br />

**Lecture 06 - September 25**

<a href="./Lecture06/Lecture06.html">HTML</a>; 
<a href="./Lecture06/Lecture06.pdf">PDF</a> 
(<a href="./Lecture06/Lecture06-annotated.pdf">annotated</a>);
<a href="./Lecture06/Lecture06.pptx">PPTX</a>

<br />

---

class: inverse

## Week 04

**Lecture 07 - September 27**

<a href="./Lecture07/Lecture07.html">HTML</a>; 
<a href="./Lecture07/Lecture07.pdf">PDF</a>
(<a href="./Lecture07/Lecture07-annotated.pdf">annotated</a>);
<a href="./Lecture07/Lecture07.pptx">PPTX</a>

<br />

**Lecture 08 - October 2**

<a href="./Lecture08/Lecture08.html">HTML</a>; 
<a href="./Lecture08/Lecture08.pdf">PDF</a>;
(<a href="./Lecture08/Lecture08-annotated.pdf">annotated</a>);
<a href="./Lecture08/Lecture08.pptx">PPTX</a>

<br />

---

class: inverse

## Week 05

**Lecture 09 - October 4**

<a href="./Lecture09/Lecture09.html">HTML</a>; 
<a href="./Lecture09/Lecture09.pdf">PDF</a>;
(<a href="./Lecture09/Lecture09-annotated.pdf">annotated</a>);
<a href="./Lecture09/Lecture09.pptx">PPTX</a>

<br />

**Lecture 10 - October 9**

<a href="./Lecture10/Lecture10.html">HTML</a>; 
<a href="./Lecture10/Lecture10.pdf">PDF</a>;
(<a href="./Lecture10/Lecture10-annotated.pdf">annotated</a>);
<a href="./Lecture10/Lecture10.pptx">PPTX</a>

<br />

---

class: inverse

## Week 06

**Lecture 11 - October 11**

<a href="./Lecture11/Lecture11.html">HTML</a>; 
<a href="./Lecture11/Lecture11.pdf">PDF</a>;
<a href="./Lecture11/Lecture11.pptx">PPTX</a>

<br />

**Lecture 12 - October 16**

<a href="./Lecture12/Lecture12.html">HTML</a>; 
<a href="./Lecture12/Lecture12.pdf">PDF</a>;
(<a href="./Lecture12/Lecture12-annotated.pdf">annotated</a>);
<a href="./Lecture12/Lecture12.pptx">PPTX</a>

<br />

---

class: inverse

## Week 07

**Lecture 13 - October 18**

Midterm examination.

<br />

**Lecture 14 - October 30**

<a href="./Lecture14/Lecture14.html">HTML</a>; 
<a href="./Lecture14/Lecture14.pdf">PDF</a>;
(<a href="./Lecture14/Lecture14-annotated.pdf">annotated</a>);
<a href="./Lecture14/Lecture14.pptx">PPTX</a>

<br />

---

class: inverse

## Week 08

**Lecture 15 - November 1**

<a href="./Lecture15/Lecture15.html">HTML</a>; 
<a href="./Lecture15/Lecture15.pdf">PDF</a>;
(<a href="./Lecture15/Lecture15-annotated.pdf">annotated</a>);
<a href="./Lecture15/Lecture15.pptx">PPTX</a>

<br />

**Lecture 16 - November 6**

<a href="./Lecture16/Lecture16.html">HTML</a>; 
<a href="./Lecture16/Lecture16.pdf">PDF</a>;
<a href="./Lecture16/Lecture16.pptx">PPTX</a>

<br />

---

class: inverse

## Week 09

**Lecture 17 - November 8**

<a href="./Lecture17/Lecture17.html">HTML</a>; 
<a href="./Lecture17/Lecture17.pdf">PDF</a>;
(<a href="./Lecture17/Lecture17-annotated.pdf">annotated</a>);
<a href="./Lecture17/Lecture17.pptx">PPTX</a>
(continued from Lecture 16)

<br />

**Lecture 18 - November 13**

<a href="./Lecture18/Lecture18.html">HTML</a>; 
<a href="./Lecture18/Lecture18.pdf">PDF</a>;
<a href="./Lecture18/Lecture18.pptx">PPTX</a>

<br />

---

class: inverse

## Week 10

**Lecture 19 - November 15**

<a href="./Lecture19/Lecture19.html">HTML</a>; 
<a href="./Lecture19/Lecture19.pdf">PDF</a>;
(<a href="./Lecture19/Lecture19-annotated.pdf">annotated</a>);
<a href="./Lecture19/Lecture19.pptx">PPTX</a>;
(<a href="./Lecture19/Lecture19-FindingN.pdf">Finding N</a>)

<br />

**Lecture 20 - November 20**

<a href="./Lecture20/Lecture20.html">HTML</a>; 
<a href="./Lecture20/Lecture20.pdf">PDF</a>;
(<a href="./Lecture20/Lecture20-annotated.pdf">annotated</a>);
<a href="./Lecture20/Lecture20.pptx">PPTX</a>;

<br />

---

class: inverse

## Week 11

**Lecture 21 - November 22**

<a href="./Lecture21/Lecture21.html">HTML</a>; 
<a href="./Lecture21/Lecture21.pdf">PDF</a>;
<a href="./Lecture21/Lecture21.pptx">PPTX</a>;

<br />

**Lecture 22 - November 27**

<a href="./Lecture22/Lecture22.html">HTML</a>; 
<a href="./Lecture22/Lecture22.pdf">PDF</a>;
(<a href="./Lecture22/Lecture22-annotated.pdf">annotated</a>);
<a href="./Lecture22/Lecture22.pptx">PPTX</a>;
(<a href="./Lecture22/Lecture22-R-Code.pdf">R Code</a>)

---

class: inverse

## Week 12

**Workshop 12**

<a href="toronto_ap.csv">Toronto AP Data File</a>

<br />

**Lecture 23 - November 29**

<a href="./Lecture23/Lecture23.html">HTML</a>

<br />

**Lecture 24 - December 4**

<a href="./Lecture24/Lecture24.html">HTML</a>;
<a href="./Lecture24/Lecture24.pdf">PDF</a>;
<a href="./Lecture24/Lecture24.pptx">PPTX</a>

<br />

